# This workflow will build manifest and deploy
name: Workato Recipe Promotion
on:
  push:
    branches: [qa,main]
  pull_request:
    branches: [ dev ]
jobs:
  set-github-variables:
    runs-on: ubuntu-latest
    env:
      REPO: ${{ github.event.repository.name }}
      Message:  ${{ github.event.head_commit.message }}
      UserName: ${{ github.event.head_commit.author.username }}
      GithubURL: ${{ github.event.head_commit.url }}
    steps:
      - name: Print Variables
        run: echo Repository Name is $REPO
      - run: echo  Approval Comment $Message
      - run: echo  Github Commit URL is $GithubURL
      - run: echo  Pull Request Approved by $UserName      
      
  
  call-workato-devops-recipe:
    needs: set-github-variables
    runs-on: ubuntu-latest
    steps:
      - name: Import Manifest
        run: |
            curl --request POST "https://www.workato.com/webhooks/rest/000bb560-7fea-4d01-97e8-396890b80833/run-devops-cicd-pipeline"	 -H "Content-type:application/json" -H '{"FolderId":${{ needs.Message }}, "Github-Commit-UserName":"${{ needs.UserName }}", "Github-Commit-URL":${{ needs.GithubURL }}, "GitHub-Repo-Name":${{ needs.REPO }}}' 	 
