# This workflow will build manifest and deploy
name: cicd Promotion
on:
  push:
    branches: [qa,main]
  pull_request:
    branches: [ dev ]
jobs:
  build-manifest:
    runs-on: ubuntu-latest
    env:
      zippath: ${{ github.event.review.state }}
      NUMBER: ${{ github.event.pull_request.title }}
      REPO: ${{ github.event.repository.name }}
      OWNER: ${{ github.event.repository.owner.login }}
      Message:  ${{ github.event.head_commit.message }}
      UserName: ${{ github.event.head_commit.author.username }}
      
          
    steps:
      - name: Import Manifest
        run: echo "$GITHUB_CONTEXT"
      - run: echo "$GITHUB_EVENT"
      - run: echo "$GITHUB_ACTOR"
      - run: echo  "$GITHUB_EVENT_NAME"
      - run: echo  "$REPO" 
      - run: echo  "$OWNER"      
      - run: echo  "$Message"  
      - run: echo  "$UserName"    
      - run: cat /home/runner/work/_temp/_github_workflow/event.json
      
      
