# This workflow will build manifest and deploy
name: Workato Recipe Promotion
on:
  push:
    branches: [qa,main]
  pull_request:
    branches: [ dev ]
jobs:
  build-manifest:
    runs-on: ubuntu-latest
    env:
      REPO: ${{ github.event.repository.name }}
      Message:  ${{ github.event.head_commit.message }}
      UserName: ${{ github.event.head_commit.author.username }}
      GithubURL: ${{ github.event.head_commit.url }}      
      
          
    steps:
      - name: Import Manifest
        run: echo "$GITHUB_CONTEXT"
      - run: echo "$GITHUB_EVENT"
      - run: echo "$GITHUB_ACTOR"
      - run: echo  "$GITHUB_EVENT_NAME"
      - run: echo  "$REPO" 
      - run: echo  "$OWNER"      
      - run: echo  "$Message"  
      - run: echo  "$UserName"    
      - run: |
            curl --location --request POST "https://www.workato.com/webhooks/rest/000bb560-7fea-4d01-97e8-396890b80833/run-devops-cicd-pipeline" \
            --header '{FolderId: ${{ env.Message }}, \
            "Github-Commit-UserName": "${{ env.UserName }}", \
            "Github-Commit-URL": "${{ env.GithubURL }}", \
             "GitHub-Repo-Name": "${{ env.REPO }}}' \            
            --header "Content-Type: application/json" \
  
      
      
